version: "3"
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    networks:
      - mern-network
    ports:
      - "4000:4000"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - mern-network
    ports:
      - "3000:3000"

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - mern-network
    ports:
      - "27017:27017"

networks:
  mern-network:
    driver: bridge